# Generated by Django 3.1 on 2021-07-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                    CREATE UNIQUE INDEX film_work_genre ON genre_film_work (film_work_id, genre_id);
                    CREATE UNIQUE INDEX film_work_person_role ON person_film_work (film_work_id, person_id, role);
                """,
        )
    ]
